batch_size_test: 12
batch_size_test_text: 64
batch_size_train: 20
embed_dim: 256
image_res: 384
image_root: images/RSTPReid
k_test: 128
max_tokens: 70
optimizer: {lr: 3e-05, lr_mult: 2, opt: adamW, weight_decay: 0.01}
patch_size: 32
schedular: {epochs: 10, lr: 3e-05, num_warmup_steps: 0.1, sched: linear}
temp: 0.07
text_config: configs/config_bert.json
text_encoder: data/bert-base-uncased
use_clip_vit: false
use_roberta: false
use_swin: true
vision_config: configs/config_swinB_384.json
only_text2image: true